export const DEFAULT_THRESHOLDS = {
  HIGH_PRIORITY_DELTA: 15,
  MEDIUM_PRIORITY_DELTA: 10,
  LOW_PRIORITY_DELTA: 5,
  MINIMUM_PASSING_SCORE: 70,
  EXACT_KEYWORD_PENALTY: 15,
  FORMATTING_ISSUE_PENALTY: 20
};
